import { useUserConversationsQuery } from '@/core/apollo/generated/apollo-hooks';
import { RoomType } from '@/core/apollo/generated/graphql-schema';
import { useCurrentUserContext } from '@/domain/community/userCurrent/useCurrentUserContext';
import { mapMessageReactions, mapMessageSender } from '@/main/userMessaging/models';
import { useUserMessagingContext } from '@/main/userMessaging/UserMessagingContext';
import { isGuidanceConversation, sortUnifiedConversations, type UnifiedConversation } from './dataMapper';
import { useUnifiedChatContext } from './UnifiedChatProvider';

// Server auto-generates names like "conversation-..." or "group-conversation-..." — ignore these
const isAutoGeneratedName = (name?: string) => !name || /^(conversation|group-conversation)-/.test(name);

/**
 * Unified conversation list: like the legacy `useUserConversations` but it does
 * NOT filter out the 1:1 Guidance conversation — instead it flags that row as
 * `isGuidance`/`pinned` and sorts it to the top, and its unread count flows into
 * the combined `totalUnreadCount`.
 */
export const useUnifiedConversations = () => {
  const { isEnabled, isOpen, newlyCreatedConversationId } = useUserMessagingContext();
  const { guidanceVcId } = useUnifiedChatContext();
  const { userModel: currentUser } = useCurrentUserContext();

  const skip = !isEnabled || !isOpen;

  const { data, loading, error } = useUserConversationsQuery({
    skip,
    fetchPolicy: 'cache-and-network',
  });

  const conversations: UnifiedConversation[] = (() => {
    if (!data?.me?.conversations?.conversations) {
      return [];
    }

    const mapped = data.me.conversations.conversations
      .filter(conv => conv.room)
      .map(conv => {
        // biome-ignore lint/style/noNonNullAssertion: filtered by conv.room check above
        const room = conv.room!;
        const lastMessage = room.lastMessage;

        const members = conv.members.map(member => ({
          id: member.id,
          type: member.type,
          displayName: member.profile?.displayName ?? '',
          avatarUri: member.profile?.avatar?.uri,
          url: member.profile?.url,
        }));

        const isGroup = room.type === RoomType.ConversationGroup;
        const otherMembers = members.filter(m => m.id !== currentUser?.id);

        let displayName: string | undefined;
        if (!isGroup && otherMembers.length > 0) {
          displayName = otherMembers[0].displayName;
        } else if (!isAutoGeneratedName(room.displayName)) {
          displayName = room.displayName;
        } else {
          displayName = otherMembers.map(m => m.displayName).join(', ');
        }

        const avatarUri =
          !isGroup && otherMembers.length > 0 ? otherMembers[0].avatarUri : (room.avatarUrl ?? undefined);

        const roomDisplayName = isGroup && !isAutoGeneratedName(room.displayName) ? room.displayName : undefined;

        const isGuidance = isGuidanceConversation(members, guidanceVcId);

        return {
          id: conv.id,
          roomId: room.id,
          isGroup,
          displayName,
          roomDisplayName,
          avatarUri,
          unreadCount: room.unreadCount,
          messagesCount: room.messagesCount,
          createdDate: new Date(room.createdDate),
          lastMessage: lastMessage
            ? {
                id: lastMessage.id,
                message: lastMessage.message,
                timestamp: lastMessage.timestamp,
                sender: mapMessageSender(lastMessage.sender),
                reactions: mapMessageReactions(lastMessage.reactions),
              }
            : undefined,
          members,
          isGuidance,
          pinned: isGuidance,
        } satisfies UnifiedConversation;
      });

    return sortUnifiedConversations(mapped, newlyCreatedConversationId);
  })();

  const totalUnreadCount = conversations.filter(conv => conv.unreadCount > 0).length;

  return {
    conversations,
    totalUnreadCount,
    isLoading: loading,
    error,
  };
};
