files:
  - source: /src/core/i18n/en/translation.en.json  # Path in Crowdin
    translation: /src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json  # Path in Crowdin
    export_pattern: /src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json  # Map to local project structure
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
