files:
  - source: /src/core/i18n/en/translation.en.json
    translation: /src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN