files:
  - source: /src/core/i18n/en/translation.en.json
    translation: /src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json
    # Add this to map the file in Crowdin to the actual file path in your repository
    export_pattern: '/develop/src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json'
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
