version: '3.9'

networks:
  alkemio_client_net:

volumes:
  alkemio_client_mysql_db:

services:
  traefik:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: alkemio_client_traefik
    image: traefik:v2.4.9
    restart: always
    ports:
      - 8888:8080
      - 3000:80
      - 3306:3306
    networks:
      - alkemio_client_net
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ./.build/traefik/
        target: /etc/traefik/

  mysql_db:
    container_name: alkemio_client_mysql_db
    image: mysql:8.0.11
    networks:
      - alkemio_client_net
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: always
    ports:
      - 3306
    volumes:
      - alkemio_client_mysql_db:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /bootstrap_scripts/1.sql

  kratos_migrate:
    container_name: alkemio_client_kratos_migrate
    image: oryd/kratos:v0.6.1-alpha.1
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    restart: on-failure
    networks:
      - alkemio_client_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: alkemio_client_kratos
    image: oryd/kratos:v0.6.1-alpha.1
    depends_on:
      - kratos_migrate
    ports:
      - 4433
      - 4434
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://localhost:3000/identity/ory/kratos/public
    networks:
      - alkemio_client_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  oathkeeper:
    container_name: alkemio_client_oathkeeper
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455
      - 4456
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - alkemio_client_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"

  ipfs:
    container_name: alkemio_client_ipfs
    image: ipfs/go-ipfs
    networks:
      - alkemio_client_net
    restart: always
    ports:
      - 4001
      - 4002
      - 5001
      - 8080
    volumes:
      - /tmp/ipfs-docker-data:/data/ipfs

  alkemio_server:
    container_name: alkemio_client_server
    image: alkemio/server:v0.11.8
    depends_on:
      - mysql_db
      - ipfs
    networks:
      - alkemio_client_net
    environment:
      - AUTH_ENABLED
      - NODE_ENV
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS=mysql_db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - GRAPHQL_ENDPOINT_PORT=4000
      - IPFS_ENDPOINT=http://ipfs:5001
      - IPFS_CLIENT_ENDPOINT=http://localhost:3000/ipfs
      - AUTH_ORY_KRATOS_ISSUER=http://alkemio-demo/
      - AUTH_ORY_KRATOS_JWKS_URI=http://oathkeeper:4456/.well-known/jwks.json
      - AUTH_ORY_KRATOS_PUBLIC_BASE_URL=http://localhost:3000/identity/ory/kratos/public
      - AUTH_ORY_KRATOS_PUBLIC_BASE_URL_SERVER=http://kratos:4433/
      - CORS_ENABLED=false
      - LOGGING_LEVEL_CONSOLE=verbose
      - LOGGING_CONSOLE_ENABLED=true
    restart: always
    ports:
      - 4000
    command: sh -c "/wait && /create_db.sh && npm run migration:run && npm start"
