kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: ct-web-deployment
  labels:
    app: ct-web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-web
  template:
    metadata:
      labels:
        app: ct-web
    spec:
      containers:
        - name: ct-web
          image: ct-web
          envFrom:
            - secretRef:
                name: ct-secrets
            - configMapRef:
                name: ct-config
          ports:
            - name: web
              containerPort: 80

