kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alkemio-web-deployment
  labels:
    app: alkemio-web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkemio-web
  template:
    metadata:
      labels:
        app: alkemio-web
    spec:
      containers:
        - name: alkemio-web
          image: alkemio.azurecr.io/alkemio-web:latest
          envFrom:
            - secretRef:
                name: alkemio-secrets
            - configMapRef:
                name: alkemio-config
          ports:
            - name: web
              containerPort: 80
