export const PLATFORM_NAVIGATION_ITEM_ELEVATION = 3;

export const PLATFORM_NAVIGATION_MENU_ELEVATION = 12;

export const PLATFORM_NAVIGATION_MENU_Z_INDEX = 1400; // MUI Modal used in Space dialogs has 1300
