import { useEffect } from 'react';
import { useUserConversationsQuery } from '@/core/apollo/generated/apollo-hooks';
import { type ActorType, RoomType } from '@/core/apollo/generated/graphql-schema';
import { useCurrentUserContext } from '@/domain/community/userCurrent/useCurrentUserContext';
import { useGuidanceVcId } from '@/main/guidance/chatWidget/useGuidanceVcId';
import { type ConversationMessage, mapMessageReactions, mapMessageSender } from './models';
import { useUserMessagingContext } from './UserMessagingContext';

export interface ConversationMember {
  id: string;
  type: ActorType;
  displayName: string;
  avatarUri?: string;
  url?: string;
}

export interface UserConversation {
  id: string;
  roomId: string;
  isGroup: boolean;
  displayName?: string;
  /** Raw room displayName from server (undefined when auto-generated). Use for editing, not display. */
  roomDisplayName?: string;
  avatarUri?: string;
  unreadCount: number;
  messagesCount: number;
  createdDate: Date;
  lastMessage?: ConversationMessage;
  members: ConversationMember[];
}

// Server auto-generates names like "conversation-..." or "group-conversation-..." — ignore these
const isAutoGeneratedName = (name?: string) => !name || /^(conversation|group-conversation)-/.test(name);

export const useUserConversations = () => {
  const { isEnabled, isOpen, newlyCreatedConversationId } = useUserMessagingContext();
  const { userModel: currentUser } = useCurrentUserContext();
  const { guidanceVcId } = useGuidanceVcId({ skip: !isEnabled || !isOpen });

  const skip = !isEnabled || !isOpen;

  const { data, loading, error } = useUserConversationsQuery({
    skip,
    fetchPolicy: 'cache-and-network',
  });

  useEffect(() => {
    // biome-ignore lint/suspicious/noConsole: debug logging
    console.log('[FullConvQuery] Skip conditions:', { isEnabled, isOpen, skip });
  }, [isEnabled, isOpen, skip]);

  useEffect(() => {
    if (skip) return;
    // biome-ignore lint/suspicious/noConsole: debug logging
    console.log('[FullConvQuery] Query state:', { loading, hasError: !!error, hasData: !!data });
    if (data?.me?.conversations?.conversations) {
      const convs = data.me.conversations.conversations;
      // biome-ignore lint/suspicious/noConsole: debug logging
      console.log(
        '[FullConvQuery] Raw data:',
        convs.map(c => ({
          id: c.id.slice(0, 8),
          roomId: c.room?.id?.slice(0, 8),
          unreadCount: c.room?.unreadCount,
        }))
      );
    }
  }, [data, loading, error, skip]);

  const conversations = (() => {
    if (!data?.me?.conversations?.conversations) {
      return [];
    }

    return (
      data.me.conversations.conversations
        .filter(conv => conv.room)
        // Temporary: hide the guidance chat with the ChatGuidance Virtual Contributor from the conversations list
        .filter(conv => !guidanceVcId || !conv.members.some(m => m.id === guidanceVcId))
        .map(conv => {
          // biome-ignore lint/style/noNonNullAssertion: filtered by conv.room check above
          const room = conv.room!;
          const lastMessage = room.lastMessage;

          const members = conv.members.map(member => ({
            id: member.id,
            type: member.type,
            displayName: member.profile?.displayName ?? '',
            avatarUri: member.profile?.avatar?.uri,
            url: member.profile?.url,
          }));

          const isGroup = room.type === RoomType.ConversationGroup;
          const otherMembers = members.filter(m => m.id !== currentUser?.id);

          // For 1:1 chats: use the other member's name
          // For groups: use server name if meaningful, otherwise join member names
          let displayName: string | undefined;
          if (!isGroup && otherMembers.length > 0) {
            displayName = otherMembers[0].displayName;
          } else if (!isAutoGeneratedName(room.displayName)) {
            displayName = room.displayName;
          } else {
            displayName = otherMembers.map(m => m.displayName).join(', ');
          }

          // For 1:1 chats: use the other member's avatar; for groups: use room avatarUrl (composite avatar handles the fallback)
          const avatarUri =
            !isGroup && otherMembers.length > 0 ? otherMembers[0].avatarUri : (room.avatarUrl ?? undefined);

          // Raw room displayName for editing (undefined when auto-generated)
          const roomDisplayName = isGroup && !isAutoGeneratedName(room.displayName) ? room.displayName : undefined;

          return {
            id: conv.id,
            roomId: room.id,
            isGroup,
            displayName,
            roomDisplayName,
            avatarUri,
            unreadCount: room.unreadCount,
            messagesCount: room.messagesCount,
            createdDate: new Date(room.createdDate),
            lastMessage: lastMessage
              ? {
                  id: lastMessage.id,
                  message: lastMessage.message,
                  timestamp: lastMessage.timestamp,
                  sender: mapMessageSender(lastMessage.sender),
                  reactions: mapMessageReactions(lastMessage.reactions),
                }
              : undefined,
            members,
          };
        })
        // Sort conversations: newly created first, then by most recent activity
        .sort((a, b) => {
          // Newly created conversation always at the top
          if (a.id === newlyCreatedConversationId) return -1;
          if (b.id === newlyCreatedConversationId) return 1;

          // Sort by most recent activity: lastMessage timestamp if available, otherwise createdDate
          const aTime = a.lastMessage ? a.lastMessage.timestamp : a.createdDate.getTime();
          const bTime = b.lastMessage ? b.lastMessage.timestamp : b.createdDate.getTime();
          return bTime - aTime;
        })
    );
  })();

  const totalUnreadCount = (() => {
    return conversations.filter(conv => conv.unreadCount > 0).length;
  })();

  return {
    conversations,
    totalUnreadCount,
    isLoading: loading,
    error,
  };
};
