import { useUserConversationsQuery } from '@/core/apollo/generated/apollo-hooks';
import { useUserMessagingContext } from './UserMessagingContext';
import { useMemo } from 'react';
import { ConversationMessage, mapMessageReactions, mapMessageSender } from './models';
import { ActorType } from '@/core/apollo/generated/graphql-schema';
import { useCurrentUserContext } from '@/domain/community/userCurrent/useCurrentUserContext';

export interface ConversationMember {
  id: string;
  type: ActorType;
  displayName: string;
  avatarUri?: string;
  url?: string;
}

export interface UserConversation {
  id: string;
  roomId: string;
  displayName?: string;
  avatarUri?: string;
  unreadCount: number;
  messagesCount: number;
  lastMessage?: ConversationMessage;
  members: ConversationMember[];
}

// Server auto-generates names like "conversation-..." or "group-conversation-..." — ignore these
const isAutoGeneratedName = (name?: string) => !name || /^(conversation|group-conversation)-/.test(name);

export const useUserConversations = () => {
  const { isEnabled, isOpen, newlyCreatedConversationId } = useUserMessagingContext();
  const { userModel: currentUser } = useCurrentUserContext();

  const { data, loading, error } = useUserConversationsQuery({
    skip: !isEnabled || !isOpen,
    fetchPolicy: 'cache-and-network',
  });

  const conversations = useMemo<UserConversation[]>(() => {
    if (!data?.me?.conversations?.conversations) {
      return [];
    }

    return (
      data.me.conversations.conversations
        .filter(conv => conv.room)
        .map(conv => {
          const room = conv.room!;
          const lastMessage = room.lastMessage;

          const members = conv.members.map(member => ({
            id: member.id,
            type: member.type,
            displayName: member.profile?.displayName ?? '',
            avatarUri: member.profile?.avatar?.uri,
            url: member.profile?.url,
          }));

          const isGroup = members.length > 2;
          const otherMembers = members.filter(m => m.id !== currentUser?.id);

          // For 1:1 chats: use the other member's name
          // For groups: use server name if meaningful, otherwise join member names
          let displayName: string | undefined;
          if (!isGroup && otherMembers.length > 0) {
            displayName = otherMembers[0].displayName;
          } else if (!isAutoGeneratedName(room.displayName)) {
            displayName = room.displayName;
          } else {
            displayName = otherMembers.map(m => m.displayName).join(', ');
          }

          // For 1:1 chats: use the other member's avatar; for groups: use first member's
          const avatarUri = !isGroup && otherMembers.length > 0 ? otherMembers[0].avatarUri : members[0]?.avatarUri;

          return {
            id: conv.id,
            roomId: room.id,
            displayName,
            avatarUri,
            unreadCount: room.unreadCount,
            messagesCount: room.messagesCount,
            lastMessage: lastMessage
              ? {
                  id: lastMessage.id,
                  message: lastMessage.message,
                  timestamp: lastMessage.timestamp,
                  sender: mapMessageSender(lastMessage.sender),
                  reactions: mapMessageReactions(lastMessage.reactions),
                }
              : undefined,
            members,
          };
        })
        // Sort conversations: newly created first, then unread, then by last message timestamp
        .sort((a, b) => {
          // Newly created conversation always at the top
          if (a.id === newlyCreatedConversationId) return -1;
          if (b.id === newlyCreatedConversationId) return 1;

          // Unread conversations first
          if (a.unreadCount > 0 && b.unreadCount === 0) return -1;
          if (a.unreadCount === 0 && b.unreadCount > 0) return 1;

          // Conversations without messages go to the end
          if (!a.lastMessage && !b.lastMessage) return 0;
          if (!a.lastMessage) return 1;
          if (!b.lastMessage) return -1;
          // Both have messages - sort by most recent first
          return b.lastMessage.timestamp - a.lastMessage.timestamp;
        })
    );
  }, [data?.me?.conversations?.conversations, newlyCreatedConversationId, currentUser?.id]);

  const totalUnreadCount = useMemo(() => {
    return conversations.filter(conv => conv.unreadCount > 0).length;
  }, [conversations]);

  return {
    conversations,
    totalUnreadCount,
    isLoading: loading,
    error,
  };
};
