export enum EntityPageSection {
  Root = '',
  Home = 'home',
  Dashboard = 'dashboard',
  Custom = 'custom',
  Settings = 'settings',
  About = 'about',
  Collaboration = 'collaboration',
  Community = 'community',
  Contribute = 'contribute',
  KnowledgeBase = 'knowledge-base',
  Subspaces = 'subspaces',
  Profile = 'profile',
  Share = 'share',
  Search = 'search',
  Updates = 'updates',
}
