fragment OrganizationInfo on Organization {
  id
  contactEmail
  domain
  authorization {
    id
    myPrivileges
  }
  roleSet {
    id
    myMembershipStatus
    applicationForm {
      id
      description
      questions {
        question
        required
        maxLength
        sortOrder
        explanation
      }
    }
  }
  settings {
    membership {
      allowUsersMatchingDomainToJoin
      allowApplications
    }
  }
  myAssociateEligibility {
    canApply
    canJoinDirectly
    reason
  }
  verification {
    id
    status
  }
  website
  profile {
    id
    url
    displayName
    description
    tagline
    avatar: visual(type: AVATAR) {
      ...VisualModel
      alternativeText
    }
    tagsets {
      ...TagsetDetails
    }
    references {
      id
      name
      uri
      description
    }
    location {
      ...fullLocation
    }
  }
  metrics {
    id
    name
    value
  }
}
