export enum SettingsSection {
  About = 'about',
  Index = 'profile',
  Community = 'community',
  Communications = 'communications',
  Authorization = 'authorization',
  Subspaces = 'subspaces',
  Subsubspaces = 'subsubspaces',
  Templates = 'templates',
  Storage = 'storage',
  SpaceSettings = 'space-settings',
  MyProfile = 'my-profile',
  Membership = 'membership',
  Organizations = 'organizations',
  Notifications = 'notifications',
  Credentials = 'credentials',
  InnovationFlow = 'innovation-flow',
  Account = 'account',
  Settings = 'settings',
}
