import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  CalloutContributionType,
  CalloutFramingType,
  CalloutVisibility,
  type CollaboraDocumentType,
  PollResultsDetail,
  PollResultsVisibility,
} from '@/core/apollo/generated/graphql-schema';
import { AddPostModal } from '@/crd/forms/callout/AddPostModal';
import { CalloutContributionSettings } from '@/crd/forms/callout/CalloutContributionSettings';
import { CalloutVisibilitySelector } from '@/crd/forms/callout/CalloutVisibilitySelector';
import {
  CollaboraDocumentTypePicker,
  type CollaboraDocumentTypeValue,
} from '@/crd/forms/callout/CollaboraDocumentTypePicker';
import { MarkdownEditor } from '@/crd/forms/markdown/MarkdownEditor';
import type { CalloutCreationTypeWithPreviewImages } from '@/domain/collaboration/calloutsSet/useCalloutCreation/useCalloutCreationWithPreviewImages';
import { useCalloutCreationWithPreviewImages } from '@/domain/collaboration/calloutsSet/useCalloutCreation/useCalloutCreationWithPreviewImages';
import useUploadMediaGalleryVisuals from '@/domain/collaboration/mediaGallery/useUploadMediaGalleryVisuals';
import { useCrdCalloutForm } from '../hooks/useCrdCalloutForm';
import { FramingEditorConnector } from './FramingEditorConnector';

type CalloutFormConnectorProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  calloutsSetId?: string;
  onFindTemplate?: () => void;
};

const CONTRIBUTION_TYPE_MAP: Record<string, CalloutContributionType> = {
  post: CalloutContributionType.Post,
  memo: CalloutContributionType.Memo,
  whiteboard: CalloutContributionType.Whiteboard,
  link: CalloutContributionType.Link,
};

const ATTACHMENT_TO_FRAMING_TYPE: Record<string, CalloutFramingType> = {
  none: CalloutFramingType.None,
  whiteboard: CalloutFramingType.Whiteboard,
  memo: CalloutFramingType.Memo,
  cta: CalloutFramingType.Link,
  image: CalloutFramingType.MediaGallery,
  poll: CalloutFramingType.Poll,
  document: CalloutFramingType.CollaboraDocument,
};

export function CalloutFormConnector({ open, onOpenChange, calloutsSetId, onFindTemplate }: CalloutFormConnectorProps) {
  const { t } = useTranslation('crd-space');
  const { values, errors, setField, validate, reset } = useCrdCalloutForm();
  const [activeAttachment, setActiveAttachment] = useState('none');

  const { handleCreateCallout, loading } = useCalloutCreationWithPreviewImages({ calloutsSetId });
  const { uploadMediaGalleryVisuals, uploading: mediaGalleryUploading } = useUploadMediaGalleryVisuals();

  const mapFormToCallout = (visibility: CalloutVisibility): CalloutCreationTypeWithPreviewImages => {
    const framingType = ATTACHMENT_TO_FRAMING_TYPE[activeAttachment] ?? CalloutFramingType.None;

    const callout: CalloutCreationTypeWithPreviewImages = {
      framing: {
        type: framingType,
        profile: {
          displayName: values.title.trim(),
          description: values.description || undefined,
        },
        tags: values.tags
          ? values.tags
              .split(',')
              .map(tag => tag.trim())
              .filter(Boolean)
          : undefined,
      },
      settings: {
        visibility,
        framing: {
          commentsEnabled: values.commentsEnabled,
        },
        contribution: {
          allowedTypes: values.allowedContributionTypes.map(t => CONTRIBUTION_TYPE_MAP[t]).filter(Boolean),
        },
      },
      sendNotification: values.notifyMembers && visibility === CalloutVisibility.Published,
    };

    // Whiteboard framing — include content + preview images generated by the single-user editor
    if (framingType === CalloutFramingType.Whiteboard) {
      callout.framing.whiteboard = {
        content: values.whiteboardContent,
        profile: { displayName: values.title.trim() || t('callout.whiteboard') },
        previewSettings: values.whiteboardPreviewSettings,
        previewImages: values.whiteboardPreviewImages,
      };
    }

    // Poll framing
    if (framingType === CalloutFramingType.Poll && values.pollQuestion) {
      callout.framing.poll = {
        title: values.pollQuestion,
        options: values.pollOptions.filter(o => o.text.trim()).map(o => o.text.trim()),
        settings: {
          allowContributorsAddOptions: values.pollAllowCustomOptions,
          minResponses: 1,
          maxResponses: values.pollAllowMultiple ? 0 : 1,
          resultsVisibility: values.pollHideResultsUntilVoted
            ? PollResultsVisibility.Hidden
            : PollResultsVisibility.Visible,
          resultsDetail: values.pollShowVoterAvatars ? PollResultsDetail.Full : PollResultsDetail.Count,
        },
      };
    }

    // Collabora document framing — the server needs displayName + documentType
    // at creation time so it can provision the correct underlying document.
    if (framingType === CalloutFramingType.CollaboraDocument) {
      callout.framing.collaboraDocument = {
        displayName: values.title.trim() || t('callout.defaultDocumentName'),
        documentType: values.collaboraDocumentType,
      };
    }

    // Link framing
    if (framingType === CalloutFramingType.Link && values.linkUrl) {
      callout.framing.profile.referencesData = [
        {
          uri: values.linkUrl.trim(),
          name: values.linkDisplayName.trim() || values.linkUrl.trim(),
        },
      ];
    }

    return callout;
  };

  // Media-gallery visuals must be uploaded AFTER the callout is saved: the create
  // mutation creates the underlying MediaGallery row server-side when the framing
  // type is MediaGallery and returns its id in the response. Mirrors the MUI
  // CreateCalloutDialog flow (see useCalloutCreationWithPreviewImages for the
  // matching whiteboard/memo preview-image handling).
  const uploadPendingMediaGallery = async (
    framingType: CalloutFramingType,
    result: Awaited<ReturnType<typeof handleCreateCallout>>
  ) => {
    if (framingType !== CalloutFramingType.MediaGallery) return;
    if (!result) return;
    const mediaGalleryId = result.framing.mediaGallery?.id;
    if (!mediaGalleryId || values.mediaGalleryVisuals.length === 0) return;
    await uploadMediaGalleryVisuals({
      mediaGalleryId,
      visuals: values.mediaGalleryVisuals,
    });
  };

  const createAndUpload = async (visibility: CalloutVisibility) => {
    if (!validate()) return;
    const callout = mapFormToCallout(visibility);
    const result = await handleCreateCallout(callout);
    // If the create mutation failed, keep the form open with its values so the user
    // can retry without re-entering everything. The mutation surfaces its own error.
    if (!result) return;
    // Regardless of upload outcome, the callout exists on the server — closing the
    // form after upload (even on rejection) prevents creating a duplicate callout
    // on a second submit. Any upload failure is still surfaced via the hook's error.
    try {
      await uploadPendingMediaGallery(callout.framing.type, result);
    } finally {
      reset();
      onOpenChange(false);
    }
  };

  const handleSubmit = () => createAndUpload(CalloutVisibility.Published);
  const handleSaveDraft = () => createAndUpload(CalloutVisibility.Draft);

  return (
    <AddPostModal
      open={open}
      onOpenChange={onOpenChange}
      title={{
        value: values.title,
        onChange: v => setField('title', v),
        error: errors.title,
      }}
      descriptionSlot={
        <MarkdownEditor
          value={values.description}
          onChange={v => setField('description', v)}
          placeholder={t('forms.descriptionPlaceholder')}
        />
      }
      tags={{
        value: values.tags,
        onChange: v => setField('tags', v),
      }}
      framingEditorSlot={
        <FramingEditorConnector
          framingType={activeAttachment}
          linkUrl={values.linkUrl}
          onLinkUrlChange={v => setField('linkUrl', v)}
          linkUrlError={errors.linkUrl}
          linkDisplayName={values.linkDisplayName}
          onLinkDisplayNameChange={v => setField('linkDisplayName', v)}
          linkDisplayNameError={errors.linkDisplayName}
          pollQuestion={values.pollQuestion}
          onPollQuestionChange={v => setField('pollQuestion', v)}
          pollQuestionError={errors.pollQuestion}
          pollOptions={values.pollOptions}
          onPollOptionsChange={v => setField('pollOptions', v)}
          pollAllowMultiple={values.pollAllowMultiple}
          onPollAllowMultipleChange={v => setField('pollAllowMultiple', v)}
          pollAllowCustomOptions={values.pollAllowCustomOptions}
          onPollAllowCustomOptionsChange={v => setField('pollAllowCustomOptions', v)}
          pollHideResultsUntilVoted={values.pollHideResultsUntilVoted}
          onPollHideResultsUntilVotedChange={v => setField('pollHideResultsUntilVoted', v)}
          pollShowVoterAvatars={values.pollShowVoterAvatars}
          onPollShowVoterAvatarsChange={v => setField('pollShowVoterAvatars', v)}
          whiteboardContent={values.whiteboardContent}
          whiteboardPreviewSettings={values.whiteboardPreviewSettings}
          whiteboardConfigured={values.whiteboardConfigured}
          whiteboardTitle={values.title.trim() || t('callout.whiteboard')}
          onWhiteboardChange={(content, previewImages, previewSettings) => {
            setField('whiteboardContent', content);
            setField('whiteboardPreviewImages', previewImages ?? []);
            setField('whiteboardPreviewSettings', previewSettings);
            setField('whiteboardConfigured', true);
          }}
          mediaGalleryVisuals={values.mediaGalleryVisuals}
          onMediaGalleryVisualsChange={v => setField('mediaGalleryVisuals', v)}
        />
      }
      activeAttachment={activeAttachment}
      onAttachmentChange={setActiveAttachment}
      attachmentEditorSlot={
        activeAttachment === 'document' ? (
          <CollaboraDocumentTypePicker
            value={values.collaboraDocumentType as CollaboraDocumentTypeValue}
            onChange={v => setField('collaboraDocumentType', v as CollaboraDocumentType)}
          />
        ) : undefined
      }
      settingsSlot={
        <>
          <CalloutContributionSettings
            allowedTypes={values.allowedContributionTypes}
            onAllowedTypesChange={types => setField('allowedContributionTypes', types)}
            commentsEnabled={values.commentsEnabled}
            onCommentsEnabledChange={v => setField('commentsEnabled', v)}
          />
          <CalloutVisibilitySelector
            value={values.visibility}
            onChange={v => setField('visibility', v)}
            notifyMembers={values.notifyMembers}
            onNotifyMembersChange={v => setField('notifyMembers', v)}
          />
        </>
      }
      onSubmit={handleSubmit}
      onSaveDraft={handleSaveDraft}
      onFindTemplate={onFindTemplate}
      loading={loading || mediaGalleryUploading}
    />
  );
}
