import { ImportedDataState } from '@alkemio/excalidraw/types/data/types';

const EmptyWhiteboard: ImportedDataState = {
  type: 'excalidraw',
  version: 2,
  source: 'https://excalidraw.com',
  elements: [
    //!!
    {
      id: 'auV2vE6i5eRPtel_pimu7',
      type: 'text',
      x: 517,
      y: 304,
      width: 155.65982055664062,
      height: 25,
      angle: 0,
      strokeColor: '#000000',
      backgroundColor: 'transparent',
      fillStyle: 'hachure',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      groupIds: [],
      seed: 1010928699,
      version: 18,
      versionNonce: 525902837,
      isDeleted: false,
      boundElements: null,
      updated: 1681812097063,
      link: null,
      locked: false,
      text: 'Empty canvas :)',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      baseline: 18,
      containerId: null,
      originalText: 'Empty canvas :)',
      strokeSharpness: 'sharp',
    },
  ],
  appState: {
    gridSize: null,
    viewBackgroundColor: '#ffffff',
  },
};
//!!
export const EmptyWhiteboard2: ImportedDataState = {
  type: 'excalidraw',
  version: 2,
  source: 'https://excalidraw.com',
  elements: [
    {
      id: 'auV2vE6i5eRPtel_pimu7',
      type: 'text',
      x: 517,
      y: 304,
      width: 155.65982055664062,
      height: 25,
      angle: 0,
      strokeColor: '#000000',
      backgroundColor: 'transparent',
      fillStyle: 'hachure',
      strokeWidth: 1,
      strokeStyle: 'solid',
      roughness: 1,
      opacity: 100,
      groupIds: [],
      seed: 1010928699,
      version: 18,
      versionNonce: 525902837,
      isDeleted: false,
      boundElements: null,
      updated: 1681812097063,
      link: null,
      locked: false,
      text: 'Empty canvas :)',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      baseline: 18,
      containerId: null,
      originalText: 'Empty canvas :) 2222',
      strokeSharpness: 'sharp',
    },
  ],
  appState: {
    gridSize: null,
    viewBackgroundColor: '#ffffff',
  },
};

export default EmptyWhiteboard;
