name: Build & Deploy to Sandbox on Azure

on:
  push:
    branches: [crowdin-action]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout github Action'
        uses: actions/checkout@v3.0.2

      - name: 'Download translations'
        uses: crowdin/github-action@v1.13.1
        with:
          create_pull_request: true
          pull_request_title: 'Latest Crowdin Translations'
          pull_request_body: 'Latest Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'develop'
          localization_branch_name: 'crowdin_translations'

          command: 'download'
          command_args: '--all --verbose'
          source: ./src/core/i18n/en/translation.en.json
          translation: ./src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json

          download_translations: false
          upload_sources: false
          upload_translations: false
          push_translations: false
          push_sources: false

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: 'Latest translations PR'
        uses: crowdin/github-action@v1.13.1
        with:
          # Tokens
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

          source: src/core/i18n/en/translation.en.json
          translation: src/core/i18n/%two_letters_code%/translation.%two_letters_code%.json

          # Name of the branch to create for the PR
          localization_branch_name: crowdin-translations

          # Create a branch and a PR on any changes
          download_translations: true
          create_pull_request: true

          # Set PR labels
          pull_request_labels: "translations"

          # For testing purposes
          # dryrun_action: true

          pull_request_base_branch_name: 'develop'

#          upload_sources: false
#          upload_translations: false
#          push_translations: false
#          push_sources: false
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1.0.1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }}
      - uses: Azure/aks-set-context@v3.2
        with:
          cluster-name: k8s-sandbox
          resource-group: res-grp-k8s-sandbox

      - uses: Azure/k8s-create-secret@v4.0
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-web-secret

      - uses: Azure/k8s-deploy@v4.10
        with:
          manifests: |
            manifests/26-web-deployment-test.yaml
            manifests/30-web-service.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-web:${{ github.sha }}
          imagepullsecrets: |
            alkemio-web-secret
