name: Docker Image CI for test infra

on:
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build --build-arg ARG_GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT_ARG}} --build-arg ARG_AUTH_REDIRECT_URI=${{ secrets.ARG_AUTH_REDIRECT_URI}} --build-arg ARG_AUTHENTICATION_ENABLE=${{ secrets.ARG_AUTHENTICATION_ENABLE}} --build-arg ARG_AUTH_CLIENT_ID=${{ secrets.ARG_AUTH_CLIENT_ID}} --build-arg ARG_AUTH_TENANT_ID=${{ secrets.ARG_AUTH_TENANT_ID}} --build-arg ARG_AUTH_API_SCOPE=${{ secrets.ARG_AUTH_API_SCOPE}} -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-web:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-web:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-web:${{ github.sha }}
            
        - uses: Azure/aks-set-context@v1
          with:
            creds: ${{ secrets.AZURE_CRED_K8S_TEST }}
            cluster-name: ${{ secrets.CLUSTER_NAME_TEST }}
            resource-group: ${{ secrets.RESOURCE_GROUP_K8S_TEST }}

        - uses: Azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: ct-web-secret

        - uses: Azure/k8s-deploy@v1
          with:
            manifests: |
              manifests/25-web-deployment.yaml
              manifests/30-web-service.yaml
            images: |
              ${{ secrets.REGISTRY_LOGIN_SERVER }}/ct-web:${{ github.sha }}
            imagepullsecrets: |
              ct-web-secret
